# -*- coding: utf-8 -*-
"""
Project : Credit Data Dataset
Script  : 05_CN2_Rule_Learning.py
Purpose : Build a CN2 rule-based classification model and evaluate
          its predictive performance on the Credit Data dataset.
Author  : Lucas Dutra Mendes
"""

# In[ ]: Import Required Packages

import Orange  # Data mining, rule learning, and evaluation

# In[ ]: Load the Dataset

# Load the Credit Data dataset prepared for rule learning
base = Orange.data.Table(
    "credit_data_regras.csv")

# Display the dataset domain
base.domain

# In[ ]: Train/Test Split

# Split the dataset into training and testing sets
base_split = Orange.evaluation.testing.sample(
    base,
    n=0.25)

# Separate the training and testing datasets
base_test = base_split[0]
base_training = base_split[1]

# Display dataset sizes
len(base_training), len(base_test)

# In[ ]: CN2 Rule Learning

# Create the CN2 rule learner
cn2 = Orange.classification.rules.CN2Learner()

# Train the rule-based model
rules = cn2(base_training)

# In[ ]: Rule Inspection

# Display the rules generated by the CN2 learner
for rule in rules.rule_list:
    print(rule)

# In[ ]: Model Prediction

# Generate predictions on the test dataset
prediction = Orange.evaluation.testing.TestOnTestData(
    base_training,
    base_test,
    [lambda testdata: rules])

# Display prediction results
prediction

# In[ ]: Model Evaluation

# Calculate classification accuracy
accuracy = Orange.evaluation.CA(prediction)

print("Accuracy:", accuracy)

# In[ ]: Conclusion

# The CN2 rule-based model was trained using the Credit Data dataset
# and evaluated on a separate test set.

# The model achieved an accuracy of approximately 97.4% on the
# test dataset.

# The generated rules provide an interpretable representation of
# the patterns used by the model to classify credit default outcomes.

# Overall, the CN2 model provides a rule-based classification approach
# that can be compared with the other machine learning models developed
# in this project.
